platform:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    tls:
      - hosts:
          - platform.iot4h.de
        secretName: platform.iot4h.de
  imagePullSecrets:
    - name: iot4h-pullsecret
portal:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    tls:
      - hosts:
          - portal.iot4h.de
        secretName: portal.iot4h.de
  imagePullSecrets:
    - name: iot4h-pullsecret