

postgresql:
  primary:
    persistence:
      size: 10Gi
  architecture: standalone
  auth:
    database: strapi
    username:  strapi
    existingSecret: iot4h-portal-api
    secretKeys:
      #checkov:skip=CKV_SECRET_6: not an actual secret
      userPasswordKey: DATABASE_PASSWORD
      adminPasswordKey: DATABASE_PASSWORD


platform:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    tls:
      - hosts:
          - platform.iot4h.de
        secretName: platform.iot4h.de
  imagePullSecrets:
    - name: iot4h-pullsecret
portal:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    tls:
      - hosts:
          - portal-api.iot4h.de
          - portal.iot4h.de
        secretName: portal.iot4h.de
  imagePullSecrets:
    - name: iot4h-pullsecret
