{{- if .Release.IsInstall}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-api-static
type: Opaque
data:
  "ADMIN_JWT_SECRET":  {{ randAlphaNum 15 | b64enc }}
  "JWT_SECRET": {{ randAlphaNum 15 | b64enc }}
  "DATABASE_PASSWORD": {{ randAlphaNum 15 | b64enc }}

---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-api
  annotations:
      avp.kubernetes.io/path: "{{ .Release.Namespace }}:{{ include "..fullname" . }}-api-static"
  labels:
    {{- include "..labels" . | nindent 4 }}
type: Opaque
data:
  "ADMIN_JWT_SECRET":  {{ "<ADMIN_JWT_SECRET>" | b64enc }}
  "JWT_SECRET": {{ "<JWT_SECRET>" | b64enc }}
  "DATABASE_PASSWORD": {{ "<DATABASE_PASSWORD>" | b64enc }}
