{{- if .Values.createSecret }}
{{- $fullNameAPI := printf "%s-%s" (include "..fullname" .) "api" -}}
{{- $secretObject := (lookup "v1" "Secret" $.Release.Namespace $fullNameAPI ) | default dict }}
{{- $secreteData := (get $secretObject "data") | default dict }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-api
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "..labels" . | nindent 4 }}
type: Opaque
data:
  "ADMIN_JWT_SECRET":  {{ get $secreteData "ADMIN_JWT_SECRET" | default ( randAlphaNum 15 | b64enc )}}
  "JWT_SECRET": {{ get $secreteData "JWT_SECRET" | default ( randAlphaNum 15 | b64enc )}}
  "DATABASE_PASSWORD": {{ get $secreteData "DATABASE_PASSWORD" | default ( randAlphaNum 15 | b64enc )}}

{{- end }}