
{{- $services := dict "api" .Values.service.port_api "ui" .Values.service.port_ui "littlefs" .Values.service.port_littlefs }}
{{- range $service, $servicePort := $services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" $ }}-{{ $service }}
  labels:
    {{- include (printf "..labels-%s" $service) $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include (printf "..selectorLabels-%s" $service) $ | nindent 4 }}
---
{{- end}}
