apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port_ui }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels-ui" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port_api }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels-api" . | nindent 4 }}